[database.sqlite]
directory = "sqlite"

[log.file]
enabled = true
level = "info,app=debug"
style = "plain"
span = "none"
target = false
rotation = "daily"
directory = "."
prefix = "obelisk_server_daily.log"
